version: "3"

vars:
  PROJECT_NAME: fabric-second-brain
  VAULT: '{{.OBSIDIAN_VAULT | default "~/Obsidian"}}'
  PYTHON: python3

tasks:
  # Installation & Setup
  install:
    desc: Install Python dependencies
    cmds:
      - pip install -r requirements.txt

  install-fabric:
    desc: Install Fabric AI
    cmds:
      - go install github.com/danielmiessler/fabric@latest
      - fabric --setup

  setup:
    desc: Complete setup - install all dependencies
    cmds:
      - task: install
      - task: install-fabric
      - task: check-vault

  check-vault:
    desc: Check if Obsidian vault exists
    cmds:
      - |
        if [ ! -d "{{.VAULT}}" ]; then
          echo "⚠️  Vault nicht gefunden: {{.VAULT}}"
          echo "Setze OBSIDIAN_VAULT Umgebungsvariable oder erstelle den Ordner"
          exit 1
        fi
        echo "✅ Vault gefunden: {{.VAULT}}"

  # Main Workflows
  organize:
    desc: Vollständige Vault-Organisation ausführen
    cmds:
      - ./bootstrap-secondbrain.sh

  rename:
    desc: Dateien nach Regeln umbenennen
    cmds:
      - "{{.PYTHON}} organize.py rename --rules rules/rename.yaml"

  move:
    desc: Dateien in PARA-Struktur verschieben
    cmds:
      - "{{.PYTHON}} organize.py move --rules rules/categorize.yaml"

  tags:
    desc: Tags normalisieren und bereinigen
    cmds:
      - "{{.PYTHON}} organize.py tags --rules rules/tags.yaml"

  # Generators
  extract-projects:
    desc: Projekt-Tags aus Notizen extrahieren
    cmds:
      - "{{.PYTHON}} generators/project_extractor.py"

  extract-people:
    desc: Personen aus Notizen extrahieren
    cmds:
      - "{{.PYTHON}} generators/people_extractor.py"

  build-moc:
    desc: Maps of Content generieren
    cmds:
      - "{{.PYTHON}} generators/moc_builder.py"

  build-clusters:
    desc: Semantische Cluster-Maps erstellen
    cmds:
      - "{{.PYTHON}} generators/cluster_map.py"

  # Fabric AI Integration
  fabric-analyze:
    desc: Inhalte mit Fabric AI analysieren
    cmds:
      - fabric apply summarize,keywords,tags -r "{{.VAULT}}"

  fabric-categorize:
    desc: Kategorien mit Fabric AI ableiten
    cmds:
      - fabric apply categorize -r "{{.VAULT}}" -o rules/categorize.yaml

  fabric-normalize:
    desc: YAML Frontmatter normalisieren
    cmds:
      - fabric apply yaml --add-missing --normalize -r "{{.VAULT}}"

  # Cleanup
  clean:
    desc: Temporäre Dateien entfernen
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete 2>/dev/null || true

  # Git & Documentation
  commit:
    desc: Änderungen anzeigen vor Commit
    cmds:
      - git status

  docs:
    desc: Projekt-Dokumentation anzeigen
    cmds:
      - cat README.md

  help:
    desc: Verfügbare Tasks anzeigen
    cmds:
      - task --list
