version: "3"

vars:
  PROJECT_NAME: fabric-second-brain
  VAULT: '{{.OBSIDIAN_VAULT | default "~/Obsidian"}}'

tasks:
  # Installation & Setup mit uv
  install:
    desc: Install project with uv (modern Python package manager)
    cmds:
      - uv sync
      - echo "✅ Project installed with uv. All scripts are now available!"

  install-fabric:
    desc: Install Fabric AI
    cmds:
      - go install github.com/danielmiessler/fabric@latest
      - fabric --setup

  setup:
    desc: Complete setup - install uv project and Fabric AI
    cmds:
      - task: install
      - task: install-fabric

  check-vault:
    desc: Check if Obsidian vault exists
    cmds:
      - |
        if [ ! -d "{{.VAULT}}" ]; then
          echo "⚠️  Vault nicht gefunden: {{.VAULT}}"
          echo "Setze OBSIDIAN_VAULT Umgebungsvariable oder erstelle den Ordner"
          exit 1
        fi
        echo "✅ Vault gefunden: {{.VAULT}}"

  # Vault Initialization
  init-vault:
    desc: Initialisiere PARA-Struktur im Vault
    cmds:
      - uv run init-vault

  init-vault-info:
    desc: Zeige Info über bestehende Vault-Inhalte
    cmds:
      - uv run init-vault --info

  cleanup-analyze:
    desc: Analysiere Ordner die in PARA verschoben werden sollten
    cmds:
      - uv run cleanup-vault --analyze

  cleanup-dry-run:
    desc: Zeige was beim Cleanup passieren würde
    cmds:
      - uv run cleanup-vault --dry-run

  cleanup-move:
    desc: Verschiebe alte Ordner in PARA-Struktur
    cmds:
      - uv run cleanup-vault --move

  # Daily Notes
  daily-create:
    desc: Erstelle Daily Note für heute
    cmds:
      - uv run create-dailies --create --days 1

  daily-week:
    desc: Erstelle Daily Notes für die letzte Woche
    cmds:
      - uv run create-dailies --create --days 7

  daily-scan:
    desc: Zeige kürzlich geänderte Dateien
    cmds:
      - uv run create-dailies --scan --days 3

  daily-link:
    desc: Verlinke kürzlich geänderte Dateien in Daily Notes
    cmds:
      - uv run create-dailies --link-recent --days 3

  # YouTube Workflow
  yt-list-patterns:
    desc: Zeige verfügbare Fabric Patterns
    cmds:
      - uv run youtube --list-patterns

  yt-extract:
    desc: 'YouTube Video extrahieren (Nutzung: task yt-extract URL="https://youtube.com/...")'
    cmds:
      - uv run youtube {{.URL}}

  yt-wisdom:
    desc: 'YouTube mit extract_wisdom Pattern (Nutzung: task yt-wisdom URL="https://youtube.com/...")'
    cmds:
      - uv run youtube {{.URL}} --pattern extract_wisdom

  yt-summary:
    desc: 'YouTube mit AI-Summary (Nutzung: task yt-summary URL="https://youtube.com/...")'
    cmds:
      - uv run youtube {{.URL}} --ai-summary

  # Main Workflows
  organize:
    desc: Vollständige Vault-Organisation ausführen
    cmds:
      - ./bootstrap-secondbrain.sh

  rename:
    desc: Dateien nach Regeln umbenennen
    cmds:
      - uv run organize rename --rules rules/rename.yml

  move:
    desc: Dateien in PARA-Struktur verschieben
    cmds:
      - uv run organize move --rules rules/categorize.yml

  tags:
    desc: Tags normalisieren und bereinigen
    cmds:
      - uv run organize tags --rules rules/tags.yml

  # Generators
  extract-projects:
    desc: Projekt-Tags aus Notizen extrahieren
    cmds:
      - uv run project-extractor

  extract-people:
    desc: Personen aus Notizen extrahieren
    cmds:
      - uv run people-extractor

  build-moc:
    desc: Maps of Content generieren
    cmds:
      - uv run moc-builder

  build-clusters:
    desc: Semantische Cluster-Maps erstellen
    cmds:
      - uv run cluster-map

  # Fabric AI Integration
  fabric-analyze:
    desc: Inhalte mit Fabric AI analysieren
    cmds:
      - fabric apply summarize,keywords,tags -r "{{.VAULT}}"

  fabric-categorize:
    desc: Kategorien mit Fabric AI ableiten
    cmds:
      - fabric apply categorize -r "{{.VAULT}}" -o rules/categorize.yaml

  fabric-normalize:
    desc: YAML Frontmatter normalisieren
    cmds:
      - fabric apply yaml --add-missing --normalize -r "{{.VAULT}}"

  # Cleanup
  clean:
    desc: Temporäre Dateien entfernen
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete 2>/dev/null || true

  # Git & Documentation
  commit:
    desc: Änderungen anzeigen vor Commit
    cmds:
      - git status

  docs:
    desc: Projekt-Dokumentation anzeigen
    cmds:
      - cat README.md

  help:
    desc: Verfügbare Tasks anzeigen
    cmds:
      - task --list
